version: '3.5'
services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: etl:1.0.0
    working_dir: /home/outlier
    command: npm start
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:12.1-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./pg-data:/var/lib/postgresql/data
